[package]
name = "t1"
version = "0.1.0"
authors = ["fess932 <fess932@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
widestring = "0.4.3"

[lib]
name = "embed"
crate-type = ["dylib"]
